# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='key',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
