# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='key',
            field=models.IntegerField(),
        ),
    ]
