# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171202_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(),
        ),
    ]
